# Generated by Django 3.0.5 on 2020-06-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceShootings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('date', models.TextField()),
                ('manner_of_death', models.TextField()),
                ('armed', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('race', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('signs_of_mental_illness', models.IntegerField()),
                ('threat_level', models.TextField()),
                ('flee', models.TextField()),
                ('body_camera', models.IntegerField()),
            ],
        ),
    ]
